apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jjv4g92c5-python 
  janus-idp.io/tekton: jjv4g92c5-python
  backstage.io/kubernetes-id: jjv4g92c5-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jjv4g92c5-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  